---
- name: "upgrade packages"
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Unarchives the compressed artifact file
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Install dependencies
  command: npm install
  args:
    chdir: /home/ubuntu/backend
  
- name: "Executing Node app with PM2"
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu